version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    build: 
      context: .
      dockerfile: Dockerfile-web
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/node_project/views/
      o: bind

  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/node_project/dhparam/
      o: bind


networks:
  app-network:
    driver: bridge
